// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonteCarloAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonteCarloAPI.Migrations
{
    [DbContext(typeof(MonteCarloDbContext))]
    [Migration("20251113021314_AddPricingHistoryTable")]
    partial class AddPricingHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonteCarloAPI.Data.OptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AveragingType")
                        .HasColumnType("integer");

                    b.Property<int?>("BarrierDir")
                        .HasColumnType("integer");

                    b.Property<double?>("BarrierLevel")
                        .HasColumnType("double precision");

                    b.Property<int?>("BarrierOptionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DigitalCondition")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCall")
                        .HasColumnType("boolean");

                    b.Property<int?>("LookbackOptionType")
                        .HasColumnType("integer");

                    b.Property<int?>("ObservationFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("OptionType")
                        .HasColumnType("integer");

                    b.Property<int?>("RangeObservationFrequency")
                        .HasColumnType("integer");

                    b.Property<double>("Strike")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("MonteCarloAPI.Data.PricingHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Delta")
                        .HasColumnType("double precision");

                    b.Property<double>("ExecutionTimeMs")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gamma")
                        .HasColumnType("double precision");

                    b.Property<double>("InitialPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberOfPaths")
                        .HasColumnType("integer");

                    b.Property<int>("OptionId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PricedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RequestSource")
                        .HasColumnType("text");

                    b.Property<double?>("Rho")
                        .HasColumnType("double precision");

                    b.Property<double>("RiskFreeRate")
                        .HasColumnType("double precision");

                    b.Property<int>("SimMode")
                        .HasColumnType("integer");

                    b.Property<double>("StandardError")
                        .HasColumnType("double precision");

                    b.Property<double?>("Theta")
                        .HasColumnType("double precision");

                    b.Property<int>("TimeSteps")
                        .HasColumnType("integer");

                    b.Property<double>("TimeToExpiry")
                        .HasColumnType("double precision");

                    b.Property<bool>("UseMultithreading")
                        .HasColumnType("boolean");

                    b.Property<double?>("Vega")
                        .HasColumnType("double precision");

                    b.Property<double>("Volatility")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("PricedAt");

                    b.HasIndex("OptionId", "PricedAt");

                    b.ToTable("PricingHistory");
                });

            modelBuilder.Entity("MonteCarloAPI.Data.PricingHistoryEntity", b =>
                {
                    b.HasOne("MonteCarloAPI.Data.OptionEntity", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });
#pragma warning restore 612, 618
        }
    }
}
